// Vendored from code/native/shared/target_traits.hpp at c26f96b; regenerate with repro/export_rack_config.py.
#pragma once
// Generated by generate_target_traits.py from target_suite.default_target_suite(); do not hand-edit.

namespace aadsp::targets {

struct odd_smoothstep_d3 {
    static constexpr const char* name = "odd_smoothstep_d3";
    static constexpr int degree = 3;
    static constexpr bool odd_only = true;
    static constexpr bool even_only = false;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[4] = {0.0f, 1.5f, 0.0f, -0.5f};
};

struct odd_smoothstep_d7 {
    static constexpr const char* name = "odd_smoothstep_d7";
    static constexpr int degree = 7;
    static constexpr bool odd_only = true;
    static constexpr bool even_only = false;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[8] = {0.0f, 2.1875f, 0.0f, -2.1875f, 0.0f, 1.3125f, 0.0f, -0.3125f};
};

struct odd_smoothstep_d11 {
    static constexpr const char* name = "odd_smoothstep_d11";
    static constexpr int degree = 11;
    static constexpr bool odd_only = true;
    static constexpr bool even_only = false;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[12] = {0.0f, 2.70703125f, 0.0f, -4.51171875f, 0.0f, 5.4140625f, 0.0f, -3.8671875f, 0.0f, 1.50390625f, 0.0f, -0.24609375f};
};

struct even_sat_d8_C3 {
    static constexpr const char* name = "even_sat_d8_C3";
    static constexpr int degree = 8;
    static constexpr bool odd_only = false;
    static constexpr bool even_only = true;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[9] = {0.0f, 0.0f, 4.0f, 0.0f, -6.0f, 0.0f, 4.0f, 0.0f, -1.0f};
};

struct even_sat_d12_C5 {
    static constexpr const char* name = "even_sat_d12_C5";
    static constexpr int degree = 12;
    static constexpr bool odd_only = false;
    static constexpr bool even_only = true;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[13] = {0.0f, 0.0f, 6.0f, 0.0f, -15.0f, 0.0f, 20.0f, 0.0f, -15.0f, 0.0f, 6.0f, 0.0f, -1.0f};
};

struct asym_e20_od7_ed8 {
    static constexpr const char* name = "asym_e20_od7_ed8";
    static constexpr int degree = 8;
    static constexpr bool odd_only = false;
    static constexpr bool even_only = false;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[9] = {0.0f, 1.75f, 0.8f, -1.75f, -1.2f, 1.05f, 0.8f, -0.25f, -0.2f};
};

struct asym_e30_od11_ed12 {
    static constexpr const char* name = "asym_e30_od11_ed12";
    static constexpr int degree = 12;
    static constexpr bool odd_only = false;
    static constexpr bool even_only = false;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[13] = {0.0f, 1.89492187f, 1.8f, -3.15820312f, -4.5f, 3.78984375f, 6.0f, -2.70703125f, -4.5f, 1.05273438f, 1.8f, -0.172265625f, -0.3f};
};

struct absfit_d16_C3 {
    static constexpr const char* name = "absfit_d16_C3";
    static constexpr int degree = 16;
    static constexpr bool odd_only = false;
    static constexpr bool even_only = true;
    static constexpr float clamp = 1.0f;
    static constexpr float coeffs[17] = {0.0f, 0.0f, 7.39953198f, 0.0f, -70.6651293f, 0.0f, 394.259994f, 0.0f, -1199.23896f, 0.0f, 2064.67487f, 0.0f, -2008.60402f, 0.0f, 1029.03335f, 0.0f, -215.859638f};
};

} // namespace aadsp::targets

#define AADSP_POLYNOMIAL_TARGETS(X) \
    X(aadsp::targets::odd_smoothstep_d3) \
    X(aadsp::targets::odd_smoothstep_d7) \
    X(aadsp::targets::odd_smoothstep_d11) \
    X(aadsp::targets::even_sat_d8_C3) \
    X(aadsp::targets::even_sat_d12_C5) \
    X(aadsp::targets::asym_e20_od7_ed8) \
    X(aadsp::targets::asym_e30_od11_ed12) \
    X(aadsp::targets::absfit_d16_C3) \
    /* end */
